image:
  file: .gitpod.dockerfile
ports:
- port: 8001
  onOpen: notify
- port: 8002
  onOpen: notify
- port: 5432
  onOpen: ignore
- port: 3306
  onOpen: ignore
tasks:
- name: Logs
  command: >
    mysqld --daemonize;
    pg_start.sh;
    apachectl start;
    clear;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log -I /var/log/nginx/access.log -I /var/log/nginx/error.log /var/log/mysql/mysql.log -I /var/log/mysql/error.log -I ~/pg/log/pgsql.log;
- name: Terminal
  command: >
    clear;
    echo "Commands:";
    echo " * apachectl start";
    echo " * apachectl stop";
    echo " * pg_start.sh";
    echo " * pg_stop.sh";
    echo " * mysqld --daemonize";
    echo " * mysqladmin -uroot shutdown -p";
   
- before: |
    php -r "file_exists('.env') || copy('.env.example', '.env');"
    url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env  #change APP_URL and ASSET_URL to 8080 URL
  init: |
    composer install
  command: |
    npm install -g laravel-echo-server
    npm install
    php artisan key:generate --ansi
    php artisan package:discover
    php artisan serve
    php artisan migrate
    php artisan db:seed
    
